"""Report generator — daily markdown reports."""

import json
import logging
import os
from datetime import date
from pathlib import Path

log = logging.getLogger(__name__)


def generate_daily_report(
    snapshot: dict,
    portfolio_allocation: dict | None = None,
    research: dict | None = None,
    day_trades: list[dict] | None = None,
    reports_dir: str = "data/reports",
) -> str:
    """Generate a markdown daily report from a snapshot."""
    os.makedirs(reports_dir, exist_ok=True)

    today = date.today().isoformat()
    holdings = snapshot.get("holdings", [])

    lines = [
        f"# Adversarial Alpha - Daily Report ({today})",
        "",
        "## Performance Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Portfolio Value | ${snapshot['total_value']:,.2f} |",
        f"| Cash | ${snapshot['cash']:,.2f} |",
        f"| Portfolio Return | {snapshot['portfolio_return_pct']:+.2f}% |",
        f"| SPY Return | {snapshot['benchmark_return_pct']:+.2f}% |",
        f"| Alpha | {snapshot['alpha']:+.2f}% |",
        f"| Positions | {snapshot['num_positions']} |",
        "",
        "## Holdings",
        "",
        "| Ticker | Weight | Shares | Price | Avg Cost | Value | P&L | Sector |",
        "|--------|--------|--------|-------|----------|-------|-----|--------|",
    ]

    for h in holdings:
        lines.append(
            f"| {h['ticker']} | {h['weight']:.1f}% | {h['shares']:.2f} | "
            f"${h['price']:.2f} | ${h['avg_cost']:.2f} | "
            f"${h['value']:,.2f} | ${h['pnl']:+,.2f} | {h['sector']} |"
        )

    # Sector breakdown
    sectors: dict[str, float] = {}
    for h in holdings:
        sectors[h["sector"]] = sectors.get(h["sector"], 0) + h["weight"]

    lines.extend([
        "",
        "## Sector Allocation",
        "",
        "| Sector | Weight | P&L |",
        "|--------|--------|-----|",
    ])
    for sector, weight in sorted(sectors.items(), key=lambda x: x[1], reverse=True):
        # Compute sector P&L
        sector_pnl = sum(h["pnl"] for h in holdings if h["sector"] == sector)
        lines.append(f"| {sector} | {weight:.1f}% | ${sector_pnl:+,.2f} |")

    # Day trades section
    if day_trades:
        lines.extend([
            "",
            "## Day Trades",
            "",
            "| Time | Ticker | Action | Shares | Price | Value | Reason |",
            "|------|--------|--------|--------|-------|-------|--------|",
        ])
        for t in day_trades:
            lines.append(
                f"| {t.get('timestamp', '?')[:19]} | {t['ticker']} | {t['action']} | "
                f"{t['shares']:.2f} | ${t['price']:.2f} | ${t['value']:,.2f} | {t.get('reason', '')} |"
            )

    # Strategy summary from optimizer
    if portfolio_allocation:
        summary = portfolio_allocation.get("strategy_summary", "")
        if summary:
            lines.extend([
                "",
                "## Strategy Summary",
                "",
                summary,
            ])

    lines.extend(["", f"---", f"*Generated by Adversarial Alpha on {today}*"])

    report = "\n".join(lines)

    report_path = os.path.join(reports_dir, f"{today}.md")
    with open(report_path, "w") as f:
        f.write(report)
    log.info("Report saved to %s", report_path)

    return report
